[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.1"
androidx-datastore = "1.2.0"
androidx-lifecycle = "2.10.0-alpha06"
androidx-appcompat = "1.7.1"
androidx-paging = "3.3.6"
androidx-paging-compose = "3.4.0-alpha04"
composeMultiplatform = "1.10.0-rc02"
composeHotReload = "1.0.0"
material3 = "1.10.0-alpha05"
material3-adaptive = "1.3.0-alpha02"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
buildKonfig = "0.17.1"
koin = "4.1.1"
koin-annotations = "2.3.1"
ksp = "2.3.0"
supabase-bom = "3.2.6"
ktor = "3.3.3"
qrcode = "4.5.0"
camera2 = "1.5.2"
mlkit-barcode = "17.3.0"
decompose = "3.4.0"
essenity = "2.5.0"
zxing = "3.5.4"
mockk = "1.14.7"
room = "2.8.4"
sqlite = "2.6.2"
coil = "3.3.0"
kotzilla = "1.4.1"

# app versions
android-versionCode = "1"
packageVersion = "1.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidx-datastore" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
compose-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform"}
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform"}
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform"}
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform"}
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform"}
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase-bom" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt" }
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt" }

qrcode = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrcode" }
camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera2" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera2" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera2" }
mlkit-barcode = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit-barcode" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-cmp = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-cmp-experimental = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
decompose-essenity = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenity" }
decompose-essenity-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenity" }

paging = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging-compose" }

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
android-test-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeMultiplatform" }
android-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeMultiplatform" }

kotzilla-sdk-compose = { group = "io.kotzilla", name = "kotzilla-sdk-compose", version.ref = "kotzilla" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
androidx-room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }